name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker Compose services
        run: docker compose build

      - name: Run linting
        run: docker compose run --rm api ruff check .

      - name: Run pipeline
        run: docker compose run --rm pipeline

      - name: Run tests
        run: docker compose run --rm api pytest

      - name: Start API and Streamlit
        run: docker compose up -d api streamlit

      - name: Show containers
        run: docker compose ps

      - name: Show logs if failed
        if: failure()
        run: docker compose logs

      - name: Shut down
        if: always()
        run: docker compose down